### ISSUE TITLE
Conexão remota ao servidor

### ISSUE THREAD

**Issue by felipebastos** [ProjetoIntegrador2021-2/infra#1]
É interessante que haja domínio do protocolo SSH e seus comandos de cópia remota de arquivos, como o SCP.

Conseguir o usuário e senha de acesso a VM com a TI.

Vocês precisam solicitar uma VM com:

- Ubuntu Server 20.04.5 LTS
- Acesso SSH (porta 22)
- 1 GB de armazenamento (fora o sistema)

Os outros sistemas vocês mesmos vão instalar e configurar.

**Comment by vitoriajuli** [comment]
https://rockcontent.com/br/blog/ssh/#oque

**Comment by felipebastos** [comment]
@ProjetoIntegrador2021-2/infra Atualizei os comentários aqui pra facilitar vocês se comunicarem com a Profª Odara.

**Comment by vitoriajuli** [comment]
VM; https://www.redhat.com/pt-br/topics/virtualization/what-is-a-virtual-machine#:~:text=Uma%20m%C3%A1quina%20virtual%20(VM)%20ou,localizado%20on%2Dpremise%20ou%20n%C3%A3o.

**Comment by vitoriajuli** [comment]
Video mostrando como fazer a transfencia de arquivos usando o SSH:

https://youtu.be/E9jlsxYLmH8
